# Generated by Django 4.2.3 on 2023-08-30 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='basePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=250)),
                ('slug', models.SlugField(null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='codePost',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.basepost')),
                ('ninjaPoints', models.IntegerField(default=0)),
            ],
            bases=('posts.basepost',),
        ),
        migrations.CreateModel(
            name='requestPost',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.basepost')),
            ],
            bases=('posts.basepost',),
        ),
        migrations.AddField(
            model_name='basepost',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.language'),
        ),
    ]
