# Generated by Django 4.2.3 on 2023-09-03 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepost',
            name='author',
        ),
        migrations.AlterField(
            model_name='basepost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='basepost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
