# Generated by Django 4.2.3 on 2023-09-03 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_remove_basepost_author_alter_basepost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='author',
            field=models.ForeignKey(null=b'I00\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
