# Generated by Django 4.2.3 on 2023-08-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_remove_basepost_author_basepost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='basepost',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.language'),
        ),
    ]
