# Generated by Django 4.2.3 on 2023-08-24 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0005_author_alter_basepost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='author',
        ),
    ]
