# Generated by Django 4.2.3 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_alter_basepost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepost',
            options={'ordering': ['-createDate']},
        ),
        migrations.AddField(
            model_name='basepost',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='basepost',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
